#optional
name:
  Node.js Rest Api CI

  #required
  #triggers workflow with push and pull_request events
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    #required
    #sequence of tasks
    steps:
      #selects an action
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Node.js ${{ matrix.node-version }}
        #selects an action
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          nohup npm run deploy &
          echo $! > deploy_pid.txt
          
      - name: Wait and Stop Deploy
        run: |
          sleep 10
          kill -9 $(cat deploy_pid.txt) 2>/dev/null || true
          rm deploy_pid.txt
